services:
  - type: web
    name: likhon-com-bd
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn projectname.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
